# Generated by Django 5.1.10 on 2025-07-05 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_registration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistrantDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, null=True)),
                ("middle_name", models.CharField(max_length=100, null=True)),
                ("last_name", models.CharField(max_length=100, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("date_of_birth", models.DateField(null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("address_line1", models.CharField(max_length=100, null=True)),
                ("address_line2", models.CharField(max_length=100, null=True)),
                ("state", models.CharField(max_length=50, null=True)),
                ("postcode", models.CharField(max_length=10, null=True)),
                ("country", models.CharField(max_length=100, null=True)),
                ("has_travel_insurance", models.BooleanField(null=True)),
                ("repatriation_details", models.TextField(null=True)),
                ("day_phone", models.CharField(max_length=20, null=True)),
                ("cell_phone", models.CharField(max_length=20, null=True)),
                (
                    "aboriginal_torres_strait_islander",
                    models.CharField(
                        choices=[
                            ("A", "Aboriginal"),
                            ("T", "Torres Straint Islander"),
                            ("B", "Aboriginal and Torres Straint Islander"),
                            ("N", "None"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("country_of_birth", models.CharField(max_length=50, null=True)),
                ("country_of_birth_other", models.CharField(max_length=50, null=True)),
                ("speaks_english", models.BooleanField(null=True)),
                ("other_language", models.CharField(max_length=50, null=True)),
                ("emergency_contact_name", models.CharField(max_length=100, null=True)),
                (
                    "emergency_contact_phone",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "secondary_emergency_contact_name",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "secondary_emergency_contact_phone",
                    models.CharField(max_length=100, null=True),
                ),
                ("representing_state", models.CharField(max_length=50, null=True)),
                ("representing_country", models.CharField(max_length=100, null=True)),
                ("supporter_info", models.CharField(max_length=100, null=True)),
                ("transplant_types", models.CharField(max_length=100, null=True)),
                ("other_transplant_type", models.CharField(max_length=100, null=True)),
                (
                    "awaiting_transplant_type",
                    models.CharField(max_length=100, null=True),
                ),
                ("transplant_date", models.DateField(null=True)),
                ("ongoing_care_hospital", models.CharField(max_length=100, null=True)),
                ("has_pre_existing_conditions", models.BooleanField(null=True)),
                ("pre_existing_conditions_details", models.TextField(null=True)),
                ("requires_wheelchair_assistance", models.BooleanField(null=True)),
                ("has_dietary_requirements", models.BooleanField(null=True)),
                ("dietary_requirements_details", models.TextField(null=True)),
                ("wants_to_volunteer", models.BooleanField(null=True)),
                ("wants_junior_activities_info", models.BooleanField(null=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrant_details",
                        to="event_registration.registration",
                    ),
                ),
            ],
        ),
    ]
