# Generated by Django 5.1.10 on 2025-07-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_registration", "0002_registration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="age_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("under_18", "Under 18"),
                    ("18_25", "18-25"),
                    ("26_35", "26-35"),
                    ("36_50", "36-50"),
                    ("over_50", "Over 50"),
                ],
                max_length=20,
            ),
        ),
    ]
