# Generated by Django 5.1.10 on 2025-07-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_registration", "0002_registration_registrantdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrantdetail",
            name="is_user",
            field=models.BooleanField(default=False),
        ),
    ]
