# Generated by Django 5.1.10 on 2025-07-11 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_registration", "0003_alter_registration_age_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrantDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_user", models.BooleanField(default=False)),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        default="O",
                        max_length=1,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address_line1", models.CharField(blank=True, max_length=100)),
                ("address_line2", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=50)),
                ("postcode", models.CharField(blank=True, max_length=10)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("has_travel_insurance", models.BooleanField(blank=True)),
                ("repatriation_details", models.TextField(blank=True)),
                ("day_phone", models.CharField(blank=True, max_length=20)),
                ("cell_phone", models.CharField(blank=True, max_length=20)),
                (
                    "aboriginal_torres_strait_islander",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "Aboriginal"),
                            ("T", "Torres Strait Islander"),
                            ("B", "Aboriginal and Torres Strait Islander"),
                            ("N", "Neither"),
                        ],
                        max_length=1,
                    ),
                ),
                ("country_of_birth", models.CharField(blank=True, max_length=50)),
                ("country_of_birth_other", models.CharField(blank=True, max_length=50)),
                ("speaks_english", models.BooleanField(blank=True)),
                ("other_language", models.CharField(blank=True, max_length=50)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "secondary_emergency_contact_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "secondary_emergency_contact_phone",
                    models.CharField(blank=True, max_length=100),
                ),
                ("representing_state", models.CharField(blank=True, max_length=50)),
                ("representing_country", models.CharField(blank=True, max_length=100)),
                ("supporter_info", models.CharField(blank=True, max_length=100)),
                ("transplant_types", models.CharField(blank=True, max_length=100)),
                ("other_transplant_type", models.CharField(blank=True, max_length=100)),
                (
                    "awaiting_transplant_type",
                    models.CharField(blank=True, max_length=100),
                ),
                ("transplant_date", models.DateField(blank=True)),
                ("ongoing_care_hospital", models.CharField(blank=True, max_length=100)),
                ("has_pre_existing_conditions", models.BooleanField(blank=True)),
                ("pre_existing_conditions_details", models.TextField(blank=True)),
                ("requires_wheelchair_assistance", models.BooleanField(blank=True)),
                ("has_dietary_requirements", models.BooleanField(blank=True)),
                ("dietary_requirements_details", models.TextField(blank=True)),
                ("wants_to_volunteer", models.BooleanField(blank=True)),
                ("wants_junior_activities_info", models.BooleanField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "registration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrant_details",
                        to="event_registration.registration",
                    ),
                ),
            ],
        ),
    ]
