# Generated by Django 5.1.10 on 2025-07-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_registration", "0004_registrantdetail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="registrantdetail",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="registrantdetail",
            name="has_dietary_requirements",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="registrantdetail",
            name="has_pre_existing_conditions",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="registrantdetail",
            name="has_travel_insurance",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="registrantdetail",
            name="requires_wheelchair_assistance",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="registrantdetail",
            name="speaks_english",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="registrantdetail",
            name="transplant_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="registrantdetail",
            name="wants_junior_activities_info",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="registrantdetail",
            name="wants_to_volunteer",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
