# Generated by Django 5.1.10 on 2025-07-12 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "event_registration",
            "0005_remove_user_role_user_first_name_user_last_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrantdetail",
            name="middle_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="middle_name",
        ),
    ]
